LANGUAGE_MAP = {
    # Top 100+ languages by population, based on Harper College / Ethnologue data.
    # Keys are lowercase language names, values are ISO 639-3 codes.
    "akan": "aka",
    "amharic": "amh",
    "arabic": "ara",
    "assamese": "asm",
    "awadhi": "awa",
    "azerbaijani, south": "azb",
    "balochi": "bal",
    "belarusian": "bel",
    "bengali": "ben",
    "betawi": "bew",
    "bhojpuri": "bho",
    "burmese": "mya",
    "cebuano": "ceb",
    "chhattisgarhi": "hne",
    "chewa": "nya",
    "chinese": "zho",  # General, Mandarin
    "chittagonian": "ctg",
    "czech": "ces",
    "deccan": "dcc",
    "dhundari": "dhd",
    "dogri": "dgo",
    "dutch": "nld",
    "english": "eng",
    "farsi, western": "pes",
    "french": "fra",
    "fulah": "ful",
    "gan chinese": "gan",
    "german": "deu",
    "greek": "ell",
    "gujarati": "guj",
    "haitian creole": "hat",
    "hakka chinese": "hak",
    "haryanvi": "bgc",
    "hausa": "hau",
    "hiligaynon": "hil",
    "hindi": "hin",
    "hmong": "hmn",
    "hmong daw": "mww",
    "hungarian": "hun",
    "igbo": "ibo",
    "ilocano": "ilo",
    "indonesian": "ind",
    "italian": "ita",
    "japanese": "jpn",
    "javanese": "jav",
    "jinyu chinese": "cjy",
    "kannada": "kan",
    "kazakh": "kaz",
    "khmer, central": "khm",
    "kinyarwanda": "kin",
    "kirundi": "run",
    "konkani": "kok",
    "korean": "kor",
    "kurdish": "kur",
    "luyia": "luy",
    "madurese": "mad",
    "magahi": "mag",
    "maithili": "mai",
    "malagasy": "mlg",
    "malay": "msa",
    "malayalam": "mal",
    "marathi": "mar",
    "marwari": "mwr",
    "min bei chinese": "mnp",
    "min dong chinese": "cdo",
    "min nan chinese": "nan",
    "mossi": "mos",
    "nepali": "nep",
    "oriya": "ori",
    "oromo, west-central": "gaz",
    "panjabi, eastern": "pan",
    "pashto, northern": "pbu",
    "pashto, southern": "pbt",
    "polish": "pol",
    "portuguese": "por",
    "punjabi, western": "pnb",
    "quechua": "que",
    "romanian": "ron",
    "russian": "rus",
    "saraiki": "skr",
    "serbo-croatian": "hbs",
    "shona": "sna",
    "sindhi": "snd",
    "sinhala": "sin",
    "somali": "som",
    "spanish": "spa",
    "sunda": "sun",
    "swedish": "swe",
    "sylheti": "syl",
    "tagalog": "tgl",
    "tamil": "tam",
    "telugu": "tel",
    "thai": "tha",
    "turkish": "tur",
    "ukrainian": "ukr",
    "urdu": "urd",
    "uyghur": "uig",
    "uzbek, northern": "uzn",
    "vietnamese": "vie",
    "wolof": "wol",
    "wu chinese": "wuu",
    "xhosa": "xho",
    "xiang chinese": "hsn",
    "yoruba": "yor",
    "zarma": "dje",
    "zulu": "zul",
}
